### ISSUE TITLE
A better sample

### ISSUE THREAD

**Issue by aous72** [SMPTE/st428-24#16]
This may be a better sample.  
Please provide feedback on the image.
This also addresses Issue #15.  
Please rename if the file if desired.
Please check if they meet the requirement, or even re-create them.
[sample2.kdu.zip](https://github.com/SMPTE/st428-24/files/12223542/sample2.kdu.zip)
[sample2.ojph.zip](https://github.com/SMPTE/st428-24/files/12223543/sample2.ojph.zip)
[sample2.zip](https://github.com/SMPTE/st428-24/files/12223544/sample2.zip)

Thank you.

**Comment by palemieux** [comment]
@aous72 Thanks! Did you create the encodes using the following command lines:

```kdu_compress -i build/2K_sample.tiff -o build/2k_sample.kdu.j2c Creversible=yes Corder=RPCL Cblk=\{32,128\} Cmodes=HT \
  ORGtparts=R Clevels=5 ORGgen_tlm=6 -fprec 12M \
  Cprecincts=\{256,256\},\{256,256\},\{256,256\},\{256,256\},\{256,256\},\{128,128\} \
  -com "SMPTE DCDM X'Y'Z' image as defined in SMPTE ST 428-1"```

```ojph_compress -i build/2K_sample.tiff -o build/2k_sample.ojph.j2c -reversible true -prog_order RPCL -block_size \{128,32\}\
   -num_decomps 5 -tlm_marker true  -precincts \{128,128\},\{256,256\}\
   -tileparts R -bit_depth 12  -com "SMPTE DCDM X'Y'Z' image as defined in SMPTE ST 428-1"```

See #14 and #15

**Comment by aous72** [comment]
Hi Pierre,

I think so, but I don't remember now.
The important thing here is the tiff image. One can re-create the compressed images as detailed in #14 and #15.

The tiff image is 16 bit and has a gradual gradient horizontally, continuing on the following horizontal line.
The first 8 rows have
0 1 2 3 ... 2047
The next 8 rows have
2048 2049 2050 ... 4095
and so on.
If you want another arrangement, please let me know.

Kind regards,
Aous.

**Comment by palemieux** [comment]
The source image is good. I was hoping to not have to recreate the J2C, but I will if you are not sure :)

**Comment by aous72** [comment]
Please do for piece of mind.  They you can compare :)

**Comment by palemieux** [comment]
I was able to roundtrip using the following KDU CLI:

```
kdu_compress -i $SRC_FILE -o $KDU_J2C Creversible=yes Corder=RPCL Cblk="{32,128}" Cmodes=HT \
  ORGtparts=R Clevels=5 ORGgen_tlm=6 Nprecision=12 Nsigned=no \
  Cprecincts="{256,256},{256,256},{256,256},{256,256},{256,256},{128,128}" \
  -com "SMPTE DCDM X'Y'Z' image as defined in SMPTE ST 428-1"

kdu_expand -i $KDU_J2C -o $KDU_OUT
```

I was not able to roundtrip using OpenJPH:

```
ojph_compress -i $SRC_FILE -o $OJPH_J2C -reversible true -prog_order RPCL -block_size "{128,32}" \
   -num_decomps 5 -tlm_marker true  -precincts "{128,128},{256,256}" \
   -tileparts R -bit_depth 12 -com "SMPTE DCDM X'Y'Z' image as defined in SMPTE ST 428-1"

ojph_expand -i $OJPH_J2C -o $OJPH_OUT
```

**Comment by palemieux** [comment]
> The source image is good. I was hoping to not have to recreate the J2C, but I will if you are not sure :)

@aous72 There is in fact a problem with the source image: the image should consist of 12-bit code values packed in the MSBs of 16 bit words.

**Comment by aous72** [comment]
See how this one goes.
[sample2.zip](https://github.com/SMPTE/st428-24/files/13746603/sample2.zip)

**Comment by aous72** [comment]
This one should be better.
[sample2.zip](https://github.com/SMPTE/st428-24/files/13746672/sample2.zip)
