### ISSUE TITLE
Term not defined

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/st428-24#3]
Section 7:
```
Each image sequence that comprises a post-production reel shall begin with a digital head leader that has a duration of eight seconds before the First Frame of Action.
```
`First Frame of Action` not defined. Recommend changing to `first frame of action` to align with how used in RP 428-6, and no definition will be needed.

**Comment by palemieux** [comment]
What is the actual definition of "first frame of action" in RP 428-6?

**Comment by palemieux** [comment]
Oh, I guess the _first frame of action_ is the first frame that follows the digital leader.

**Comment by palemieux** [comment]
I propose removing the term, since it is not used in ST 428-14.
