### ISSUE TITLE
should COM marker refer to ST428-1, RP428-5 or ST428-24 ?

### ISSUE THREAD

**Issue by michaeldsmith** [SMPTE/st428-24#5]
Currently it says COM marker should refer to RP428-5

![image](https://github.com/SMPTE/st428-24/assets/37905569/1de726df-8655-4aa7-ba2c-c8fd585af90f)

RP428-5 is the TIFF file format for DCDM

The pixel essence in the JPEG 2000 codestream isn't conforming to the TIFF format, its conforming to the general DCDM SDR pixel essence spec, ST428-1

Shouldn't the COM marker text be changed from referencing RP428-5 to ST428-1 ?

**Comment by michaeldsmith** [comment]
I noticed that the text in the current version is duplicating the text in the image description tag of the RP428-5

![image](https://github.com/SMPTE/st428-24/assets/37905569/6912bd74-636c-4e00-afbd-edc069e985b5)

Is the intent to duplicate that here as RP428-5?  Or would it be to refer to the actual pixel essence spec ST428-1? Or actually refer to this new spec ST428-24 ?

**Comment by palemieux** [comment]
I vote for `SMPTE DCDM X'Y'Z' image as defined in SMPTE ST 428-1`
