### ISSUE TITLE
should the J2C codestream be limited to exactly one COM marker ?

### ISSUE THREAD

**Issue by michaeldsmith** [SMPTE/st428-24#6]
Its very common for JPEG 2000 encoders to include a COM marker in the output J2C codestream that includes the encoder's name and version number.  I think this happens automatically with Kakadu, OpenJPH and Clipster, there are probably other examples.

The current text says "exactly one COM marker" corresponding to this string that identifies the standard.  This may be more difficult if JPEG 2000 encoders typically also include a COM marker with the encoder version number

![image](https://github.com/SMPTE/st428-24/assets/37905569/f435681e-dc17-42d0-a5ec-4a7fa2f1f29e)

**Comment by palemieux** [comment]
Yes, the intent is to definitely allow other COM markers. The prose is ambiguous as currently drafted.

**Comment by michaeldsmith** [comment]
the current example KDU file has 3 COM markers
![image](https://github.com/SMPTE/st428-24/assets/37905569/2e462130-c244-4db2-9257-d9b9422cadc8)
